### ISSUE TITLE
Build Fails due to Conan Error

### ISSUE THREAD

**Issue by jtwine** [realmalliance/atak-docker-build#3]
The ATAK build command fails because of an error with conan.  I believe this is because conan v2 is installed instead of the older version and its command line is not compatible with the older version's command line.  The build fails here:

```
Installing collected packages: MarkupSafe, Jinja2, PyYAML, colorama, fasteners, patch-ng, six, python-dateutil, idna, 
charset-normalizer, certifi, urllib3, requests, distro, conan
Successfully installed Jinja2-3.1.2 MarkupSafe-2.1.2 PyYAML-6.0 certifi-2022.12.7 charset-normalizer-3.0.1 colorama-0.4.6
conan-2.0.0 distro-1.8.0 fasteners-0.18 idna-3.4 patch-ng-1.17.4 python-dateutil-2.8.2 requests-2.28.2 six-1.16.0 
urllib3-1.26.14
usage: conan profile [-h] [-v [V]] [--logger] {detect,list,path,show} ...
conan profile: error: argument subcommand: invalid choice: 'new' (choose from 'detect', 'list', 'path', 'show')
ERROR: Exiting with code: 2
The command '/bin/sh -c pip install conan     && conan profile new default --detect     && conan profile update
settings.compiler.version=8 default' returned a non-zero code: 2
```
Additionally, changes may be required to the **conanfile.py** files because the ```import``` statements will have to change as well as the syntax for the ```copy``` method (although these are part of the atak source distribution).  For example:
```
#from conans import ConanFile, AutoToolsBuildEnvironment, tools
#from conans.tools import load
from conan.tools.gnu import Autotools, AutotoolsToolchain, AutotoolsDeps
from conan import ConanFile, tools
from conan.tools.files import load, copy
...
#self.copy("*", dst=source + "/lib", src="../" + source + "/lib")
copy(self, pattern="*", dst=source + "/lib", src="../" + source + "/lib")
```
Technically the incompatibility with conan v2 is technically a problem with ATAK's source distribution and not your work, but if this could be modified to perhaps pull down and build/install a compatible version of conan, that might be easier?

**Comment by eugeneiiim** [comment]
Thanks @jtwine. I'll have it continue using the old version of conan (1.59).
